name: test-macOS

on:
  pull_request:
  push:
    branches:
      - master
      - canary
      - v[0-9]+.x-staging
      - v[0-9]+.x

env:
  PYTHON_VERSION: 3.8
  FLAKY_TESTS: dontcare

jobs:
  test-macOS-with-quic:
    if: github.repository == 'nodejs/node'
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Environment Information
        run: npx envinfo
      - name: Build
        run: make build-ci -j8 V=1 CONFIG_FLAGS="--error-on-warn --experimental-quic"
      - name: Test
        run: make run-ci -j8 V=1 TEST_CI_ARGS="-p actions"
