name: test-asan

on:
  push:
    branches:
      - master
      - canary
      - v[0-9]+.x-staging
      - v[0-9]+.x
    paths-ignore:
      - 'doc/**'
  pull_request:
    paths-ignore:
      - 'doc/**'

env:
  PYTHON_VERSION: 3.8
  FLAKY_TESTS: dontcare

jobs:
  test-asan:
    if: github.repository == 'nodejs/node'
    runs-on: ubuntu-latest
    env:
      CC: clang
      CXX: clang++
      LINK: clang++
      CONFIG_FLAGS: --enable-asan
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Environment Information
        run: npx envinfo
      - name: Build
        run: make build-ci -j2 V=1
      - name: Test
        run: make run-ci -j2 V=1 TEST_CI_ARGS="-p actions"
